#!/usr/bin/env bash

if [ "$1" == "--version" ]; then
	echo "v1.1.5"
	exit 0;
fi

if [ "$1" == "--help" ]; then
	echo "eslintme [options] [file.js]

Options:
  --help    Show this help menu
  --version Prints version number"
	exit 0;
fi

# figures out the path to eslint_d executable
function findeslintd() {
	source="${BASH_SOURCE[0]}"
	while [ -h "$source" ]; do
		currdir="$( cd -P "$( dirname "$source" )" && pwd )"
		source="$(readlink "$source")"
		[[ $source != /* ]] && source="$currdir/$source"
	done
	currdir="$( cd -P "$( dirname "$source" )" && pwd )"
	if hash eslint_d 2>/dev/null; then
		# use global eslint_d install
		echo eslint_d
	elif [ -e "$currdir/node_modules/eslint_d/bin/eslint_d.js" ]; then
		# nested install
		echo "$currdir/node_modules/eslint_d/bin/eslint_d.js"
	else
		# flat npm3 install
		echo "$currdir/../eslint_d/bin/eslint_d.js"
	fi
}

# forwards eslint_d commands
if [ "$1" == "stop" ]; then
	eslintexec="$(findeslintd)"
	"$eslintexec" stop
	exit 0;
fi
if [ "$1" == "start" ]; then
	eslintexec="$(findeslintd)"
	"$eslintexec" start
	exit 0;
fi
if [ "$1" == "status" ]; then
	eslintexec="$(findeslintd)"
	"$eslintexec" status
	exit 0;
fi
if [ "$1" == "restart" ]; then
	eslintexec="$(findeslintd)"
	"$eslintexec" restart
	exit 0;
fi

# gets the port of eslint_d running server
eslintdport="$(cat ~/.eslint_d_port 2> /dev/null)"

# if the server isn't running starts it and get the port
if [ -z "$eslintdport" ]; then

	eslintexec="$(findeslintd)"

	# starts the eslint_d server
	"$eslintexec" start
	eslintdport=$(cat ~/.eslint_d_port)
fi

# uses netcat to lint the file
echo "{\"cwd\":\".\",\"args\":[\"-f\",\"compact\",\"$1\"]}" | nc localhost "$eslintdport"

